(source "melpa")

(package "dashboard-ls" "0.3.0" "Display files/directories in current directory on Dashboard")

(package-file "dashboard-ls.el")

(depends-on "emacs" "24.3")
(depends-on "dashboard")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
